In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes' ]]
depandent= dataset[['charges']]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent, depandent, test_size = 1/3, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={
    'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
    'splitter':['best', 'random'],
    'max_features':['sqrt', 'log2']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [11]:
from sklearn.model_selection import GridSearchCV
print("value for best parameter:",grid.best_params_)
best_index=grid.best_index_
best_r2_score=grid.cv_results_['mean_test_score'][best_index]
print("r2:",best_r2_score)

value for best parameter: {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'best'}
r2: 0.6523547540987137

In [12]:
table=pd.DataFrame.from_dict(grid.cv_results_)

In [13]:
table[['rank_test_score', 'mean_test_score', 'params']].sort_values('rank_test_score')

,rank_test_score,mean_test_score,params
2,1,0.652355,"{'criterion': 'squared_error', 'max_features':..."
4,2,0.636379,"{'criterion': 'friedman_mse', 'max_features': ..."
6,3,0.627178,"{'criterion': 'friedman_mse', 'max_features': ..."
14,4,0.624116,"{'criterion': 'poisson', 'max_features': 'log2..."
10,5,0.614702,"{'criterion': 'absolute_error', 'max_features'..."
15,6,0.607120,"{'criterion': 'poisson', 'max_features': 'log2..."
12,7,0.593388,"{'criterion': 'poisson', 'max_features': 'sqrt..."
0,8,0.592546,"{'criterion': 'squared_error', 'max_features':..."
3,9,0.590459,"{'criterion': 'squared_error', 'max_features':..."
7,10,0.584418,"{'criterion': 'friedman_mse', 'max_features': ..."
9,11,0.582452,"{'criterion': 'absolute_error', 'max_features'..."
8,12,0.575630,"{'criterion': 'absolute_error', 'max_features'..."
11,13,0.568416,"{'criterion': 'absolute_error', 'max_features'..."
1,14,0.536133,"{'criterion': 'squared_error', 'max_features':..."
13,15,0.499457,"{'criterion': 'poisson', 'max_features': 'sqrt..."
5,16,0.473721,"{'criterion': 'friedman_mse', 'max_features': ..."

In [ ]:
age_input=float (input("Age:"))
bmi_input=float(input("BMI"))
Children_input=float(input("children:"))
sex_male_input=int(input("sex male 0 or 1:"))
smoker_yes_input=int(input("smoker yes 0 or 1:"))

In [ ]:
best_model = grid.best_estimator_

In [ ]:
import pickle
filename="finalized_DecisionTreeRegressor.sav"
pickle.dump(best_model,open(filename, 'wb'))

In [ ]:
loaded_model=pickle.load(open("finalized_DecisionTreeRegressor.sav",'rb'))
result = loaded_model.predict([[19,27.900,0,0,1]])
print(result)