In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=dataset.drop("sg",axis=1)
dataset

,age,bp,al,su,rbc,pc,pcc,ba,bgr,bu,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,57.482105,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,22.000000,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,23.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,16.000000,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,25.000000,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,36.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,68.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,115.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,80.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,49.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'rbc_normal', 'pc_normal', 'pcc_present', 'ba_present',
       'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes',
       'classification_yes'],
      dtype='object')

In [6]:
 independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'rbc_normal', 'pc_normal', 'pcc_present', 'ba_present',
       'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes']]
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [7]:

dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [8]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
independent.shape

(399, 23)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [12]:
# SVM classifie object

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
param_grid={
    'kernel':['linear','rbf','poly','sigmoid'],
    'gamma':['auto','scale'],
    'C':[10,100,1000,2000,]} 

grid = GridSearchCV(SVC(probability=True), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)
re=grid.cv_results_
grid_prediction=grid.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_prediction)
print("the confusion Matrix:\n",cm)
print("The is SVM:\n",clf_report)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
the confusion Matrix:
 [[51  0]
 [ 1 81]]
The is SVM:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [13]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [14]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.018126,0.010252,0.011456,0.003157,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.908877,0.923510,0.962573,0.961826,1.000000,0.951357,0.032192,18
1,0.009481,0.001265,0.011744,0.002529,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.908877,0.981014,0.962573,0.981031,1.000000,0.966699,0.031240,3
2,0.016459,0.001825,0.010907,0.001172,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.945100,0.961755,0.981217,0.981031,0.981031,0.970027,0.014541,1
3,0.010864,0.004239,0.010403,0.002268,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.908877,0.981014,0.981217,0.981031,0.981031,0.966634,0.028879,5
4,0.009697,0.001343,0.011744,0.003848,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.908877,0.923510,0.962573,0.961826,1.000000,0.951357,0.032192,18
5,0.010446,0.001392,0.009675,0.001549,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.908877,0.981014,0.962573,0.981031,1.000000,0.966699,0.031240,3
6,0.013926,0.003184,0.009275,0.002330,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.945100,0.961755,0.981217,0.981031,0.981031,0.970027,0.014541,1
7,0.006815,0.000983,0.008909,0.002221,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.908877,0.981014,0.981217,0.981031,0.981031,0.966634,0.028879,5
8,0.010508,0.002585,0.009631,0.004835,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.890759,0.885265,0.981217,0.943093,0.981217,0.936310,0.041856,31
9,0.009457,0.002297,0.009368,0.001461,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.890467,0.942166,0.981217,0.981031,1.000000,0.958976,0.039090,10
10,0.009083,0.002680,0.010491,0.001272,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.908877,0.943699,0.962573,0.981031,1.000000,0.959236,0.031386,8
11,0.008056,0.002024,0.008583,0.000781,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.908877,0.923510,0.981217,0.961826,0.961826,0.947451,0.026887,22
12,0.011973,0.002789,0.008935,0.000595,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.890759,0.885265,0.981217,0.943093,0.981217,0.936310,0.041856,31
13,0.006504,0.002966,0.009829,0.000460,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.890467,0.942166,0.981217,0.981031,1.000000,0.958976,0.039090,10
14,0.010614,0.001202,0.009642,0.001070,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.908877,0.943699,0.962573,0.981031,1.000000,0.959236,0.031386,8
15,0.006077,0.003986,0.010045,0.004065,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.908877,0.943041,0.981217,0.961826,0.961826,0.951358,0.024432,17
16,0.013340,0.005241,0.008762,0.002528,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.890759,0.905069,0.981217,0.943093,0.962264,0.936480,0.034021,27
17,0.009518,0.001128,0.008059,0.000937,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.890467,0.942166,0.981217,0.981031,1.000000,0.958976,0.039090,10
18,0.010967,0.001046,0.009611,0.001008,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.872428,0.943699,0.944023,0.924528,1.000000,0.936936,0.040959,23
19,0.007463,0.003581,0.010609,0.001308,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.945100,0.943699,0.962573,0.943093,0.961826,0.951258,0.008960,20
20,0.013899,0.008349,0.009170,0.001147,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.890759,0.905069,0.981217,0.943093,0.962264,0.936480,0.034021,27
21,0.008416,0.002578,0.009720,0.000548,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.890467,0.942166,0.981217,0.981031,1.000000,0.958976,0.039090,10
22,0.013973,0.003092,0.010227,0.001134,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.872428,0.943699,0.944023,0.924528,1.000000,0.936936,0.040959,23
23,0.006097,0.001149,0.010450,0.000373,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.945100,0.943699,0.962573,1.000000,0.961826,0.962640,0.020312,7
24,0.012017,0.004594,0.010752,0.003201,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.890759,0.905069,0.981217,0.943093,0.962264,0.936480,0.034021,27
25,0.007791,0.001585,0.011797,0.002128,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.890467,0.942166,0.981217,0.981031,1.000000,0.958976,0.039090,10
26,0.010568,0.000393,0.008697,0.000801,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.872428,0.943699,0.944023,0.924528,1.000000,0.936936,0.040959,23
27,0.008268,0.000804,0.008433,0.000353,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.945100,0.943699,0.962573,0.943093,0.961826,0.951258,0.008960,20
28,0.010362,0.004844,0.009291,0.001772,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.890759,0.905069,0.981217,0.943093,0.962264,0.936480,0.034021,27
29,0.007158,0.000845,0.009371,0.001447,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.890467,0.942166,0.981217,0.981031,1.000000,0.958976,0.039090,10
30,0.010254,0.001499,0.010268,0.001728,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.872428,0.943699,0.944023,0.924528,1.000000,0.936936,0.040959,23
31,0.009082,0.001678,0.008472,0.001317,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.945100,0.924528,0.962573,1.000000,0.961826,0.958806,0.024832,16

In [15]:
age_input=float(input("AGE:"))
BP_input=float(input("BP:"))
AL_input=float(input("AL:"))
SU_input=float(input("SU:"))
BGR_input=float(input("BGR:"))
BU_input=float(input("BU:"))
SC_input=float(input("SC:"))
SOD_input=float(input("SOD:"))
POT_input=float(input("POT:"))
HRMO_input=float(input("HROM:"))
RBC_input=float(input("RBC:"))
PC_input=float(input("PC:"))
PCC_input=float(input("PCC:"))
BA_input=float(input("BA:"))
HTN_input=float(input("HTN:"))
DM_input=float(input("DM:"))
CAD_input=float(input("CAD:"))
APPET_input=float(input("APPET:"))
PE_input=float(input("PE:"))
ANE_input=float(input("ANE:"))
PCV_input=float(input("PCV:"))
WC_input=float(input("WC:"))
RC_input=float(input("RC:"))

AGE: 43
BP: 78
AL: 3
SU: 56
BGR: 134
BU: 55
SC: 3
SOD: 123
POT: 6
HROM: 11
RBC: 1
PC: 1
PCC: 1
BA: 0
HTN: 0
DM: 1
CAD: 0
APPET: 1
PE: 1
ANE: 0
PCV: 38
WC: 890
RC: 4.9

In [36]:
import pickle
filename="finalized_SVC_.sav"
pickle.dump(grid,open(filename,'wb'))

In [38]:
loaded_model=pickle.load(open("finalized_SVC_.sav",'rb'))
result=loaded_model.predict([[45,56,5,70,123,67,1,145,4,12,0,1,0,1,0,1,0,1,0,1,31,89,3]])
print(result)

[1]