In [1]:
import numpy as np
import pandas as pd

In [3]:
dataset=pd.read_csv('insurance_pre.csv')

In [5]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [9]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [11]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [13]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={
    'criterion':['squared_error','absolute_error','friedman_mse','poisson'],
    'n_estimators':[10,50,100],
    'max_features':['sqrt','log2']
}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             verbose=3)

In [29]:
table=pd.DataFrame.from_dict(grid.cv_results_)

In [31]:
table[['rank_test_score', 'mean_test_score', 'params']].sort_values('rank_test_score')

,rank_test_score,mean_test_score,params
20,1,0.834046,"{'criterion': 'poisson', 'max_features': 'sqrt..."
23,2,0.833883,"{'criterion': 'poisson', 'max_features': 'log2..."
10,3,0.833701,"{'criterion': 'absolute_error', 'max_features'..."
5,4,0.833573,"{'criterion': 'squared_error', 'max_features':..."
17,5,0.833316,"{'criterion': 'friedman_mse', 'max_features': ..."
14,6,0.833160,"{'criterion': 'friedman_mse', 'max_features': ..."
11,7,0.833131,"{'criterion': 'absolute_error', 'max_features'..."
8,8,0.832971,"{'criterion': 'absolute_error', 'max_features'..."
4,9,0.832866,"{'criterion': 'squared_error', 'max_features':..."
1,10,0.831580,"{'criterion': 'squared_error', 'max_features':..."
22,11,0.831420,"{'criterion': 'poisson', 'max_features': 'log2..."
2,12,0.831399,"{'criterion': 'squared_error', 'max_features':..."
13,13,0.831222,"{'criterion': 'friedman_mse', 'max_features': ..."
19,14,0.831221,"{'criterion': 'poisson', 'max_features': 'sqrt..."
16,15,0.831192,"{'criterion': 'friedman_mse', 'max_features': ..."
7,16,0.830378,"{'criterion': 'absolute_error', 'max_features'..."
15,17,0.822738,"{'criterion': 'friedman_mse', 'max_features': ..."
9,18,0.820990,"{'criterion': 'absolute_error', 'max_features'..."
6,19,0.820829,"{'criterion': 'absolute_error', 'max_features'..."
0,20,0.820198,"{'criterion': 'squared_error', 'max_features':..."
18,21,0.819885,"{'criterion': 'poisson', 'max_features': 'sqrt..."
12,22,0.817113,"{'criterion': 'friedman_mse', 'max_features': ..."
3,23,0.812525,"{'criterion': 'squared_error', 'max_features':..."
21,24,0.807524,"{'criterion': 'poisson', 'max_features': 'log2..."

In [35]:
age_input=float (input("Age:"))
bmi_input=float(input("BMI"))
Children_input=float(input("children:"))
sex_male_input=int(input("sex male 0 or 1:"))
smoker_yes_input=int(input("smoker yes 0 or 1:"))

Age: 34
BMI 56
children: 1
sex male 0 or 1: 1
smoker yes 0 or 1: 1

In [37]:
best_model = grid.best_estimator_

In [39]:
import pickle
filename="finalized_DecisionTreeRegressor.sav"
pickle.dump(best_model,open(filename, 'wb'))

In [43]:
loaded_model=pickle.load(open("finalized_DecisionTreeRegressor.sav",'rb'))
result = loaded_model.predict([[28,33.000,3,0,1]])
print(result)

[34821.3758765]

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(